name: master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: s4u/setup-maven-action@v1.2.1
        with:
          checkout-fetch-depth: 0
          java-version: 17
          maven-version: 3.8.6
      - name: build the job
        id: btj
        run: |
          mvn clean install

      - name: Running the JAR file
        id: rtjf
        run: |
          cp ${{ github.workspace }}/target/Employee-0.0.1-SNAPSHOT.jar ${{ github.workspace }}/jarEmployee-0.0.1-SNAPSHOT.jar
          ls -ltr
          java -jar ${{ github.workspace }}/jarEmployee-0.0.1-SNAPSHOT.jar &

      - name: Stop the JAR
        id: stj
        run: |
         pkill -f "jarEmployee-0.0.1-SNAPSHOT.jar" || echo "process not found"
