name: master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: s4u/setup-maven-action@v1.2.1
        with:
          checkout-fetch-depth: 0
          java-version: 17
          maven-version: 3.8.6

      - name: Running the JAR file
        id: rtjf
        run: |
          cp ${{ github.workspace }}/src/target/Employee-0.0.1-SNAPSHOT.jar${{ github.workspace }}/test.jar
          ls -ltr
          java -jar test.jar
